apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-3

resources:
  - frontend.yaml
  - ingress.yaml

configMapGenerator:
  - name: frontend-config
    files:
      - config.json=config/frontend-config.json

generatorOptions:
  disableNameSuffixHash: true